### ISSUE TITLE
Frontend and Design

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#16]
To assign People to the frontend and design.

**Comment by olgierd-on-fire** [comment]
[Font Awesome - Icons](http://fontawesome.io/icons/) is awesome set of icons.

**Comment by Mortiferr** [comment]
Indeed

**Comment by olgierd-on-fire** [comment]
I try to use JavaScript to validate data and something when HTML and CSS tasks are done.

**Comment by Mortiferr** [comment]
I can handle that, I am doing the front end

**Comment by Mortiferr** [comment]
But I would appreciate help

**Comment by olgierd-on-fire** [comment]
@Mortiferr Okay then.

**Comment by Aliin** [comment]
Why don't you split it at the beginning? The more help the better, and olgierd didn't pick any task before. So Patrick you don't have to do the whole Front-end yourself but start with the HTML/CSS and Javascript functionality other than the validation, and olgierd starts on the validation. Then you can help each other on both issues and improve each other's code too.

**Comment by olgierd-on-fire** [comment]
@Aliin Maybe we need to split more. @Mortiferr can do all of frontend side I think. I'm gonna find other tasks.

**Comment by Aliin** [comment]
Yes I split off some branches to work on.

**Comment by Aliin** [comment]
http://www.yiiframework.com/doc/guide/1.1/en/basics.best-practices

**Comment by Mortiferr** [comment]
Great!

**Comment by Mortiferr** [comment]
So I should create a new branch called front end and then merge to master every now and then? Also when we get ready to start actually making releases, I will create a branch called develop which will be like the prerelease branch. And then we will merge it to master to release a new update.

**Comment by Aliin** [comment]
Exactly. But we should only merge code that works. Also the pull requests have the advantage that we can basically submit it to each other for review before it goes onto master.

**Comment by Mortiferr** [comment]
Sounds good.

**Comment by Aliin** [comment]
@Mortiferr I made some changes to the display-Posts branch. What happens now is that when you open index.php, it will Display the category names. It will refer to two files in the views/categories Folder: one Header and one footer file. You can now design the way categories will look when displayed on the first page, using HTML, CSS, and Javascript. To do that you can link to the CSS/JS files as usual on the top of the index.php file. The html that will go around the category names you can put in the mentioned "Header" and "footer" files. Basically what I did was split the html into multiple files according to MVC practice. Imagine you are taking the HTML tags you put into the Header file and copy-pasting them into the index.php file. Understanding me?

**Comment by Mortiferr** [comment]
So I create a `header.php` and a `footer.php` and then you can just add a `required "header.php"` in the main index.php and then that way we can update the header/footer on every page that way we only have to change one file, right?

**Comment by Aliin** [comment]
Nevermind. Something happened - I'm still not that good with Git - and the changes I thought I had made aren't in this repo haha. But yes, that's the plan.

**Comment by Aliin** [comment]
@Mortiferr Anyway. Maybe it's even easier if we just keep the file as it is right now until some of the frontend is ready. What you can do is 1. Just work normally on the index.php file.
2. make some html for the categories and posts. Since they go into the main page, you can just make a separate html document that does not have the html, head and body tags and only marks how to display one category. You can just write between the tags what it is supposed to display - e.g. category title or post title, username, date created, content/text. I will then replace it with the php code that displays that.

**Comment by Aliin** [comment]
e.g. something like this: Not what you should do, just an example of what your document could look like.

<div><h3>category-title</h3></div>
<div><p>content</p></div>
<div>footer: date, username, etc.</div>

**Comment by Aliin** [comment]
Argh we changed everything and using the phalcon Framework. You should best coordinate with the other two, Patrick.
