### ISSUE TITLE
Created a roadmap on the Wiki. Please review and improve.

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#18]

**Comment by olgierd-on-fire** [comment]
How to check what we finished a feature or design? Where do we start to develop?

**Comment by Aliin** [comment]
That's why I opened the issues frontend and backend. You can just assign yourself to one of the issues or make a new one, create a fork, and start writing code. Of course, you'd have to be sure it is compatible if you're writing backend, so you have to check how the database will be set up. I will finish the first Version of database-setup main later on, check if it works, and make a pull request to main. Of course, you can participate on developing the fork that sets up the database, too, just Change stuff in the fork and make a pull request (of course, don't Change it in main right away.) If you want to do frontend, you can basically do anything you want right now, just post it in the frontend issue. If you want to do backend, I'll start working on the php that gets the Posts from the database and Displays them today. One Thing you could do, for example, is work on the PHP code that submits a post and stores it in the database. I think those are the first two steps for the backend. Once they're done, we can start to add all kinds of other functionality and there will be more different things we can code and implement. What I said here goes for everyone, by the way :)

**Comment by Aliin** [comment]
Anyway if we have finished a Feature, we should make a pull request from our fork to main and also write a comment in the respective issue. But we should make Wiki pages where one can check which Features are implemented or not and which are yet to do and who is assigned to what.

**Comment by olgierd-on-fire** [comment]
Thank you, Aliin. I'm new to collaborate a project on github.

**Comment by Aliin** [comment]
Haha me too! I just didn't find anything suitable for a beginner so I decided to start my own Project. I'm still figuring things out! Anyway, whatever you want to do, feel free to do or try it! And if you have any questions you can ask me.
