### ISSUE TITLE
Comment Code

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#24]
So one of the most important aspects of writing code in a community is commenting it well. Basic commenting has a top priority if it is necessary so other developers understand what you're doing. In our case, since it is a beginner project - right now we are three people but I hope we'll find some more - I would like us to comment code in-depth so people understand what you're doing. That doesn't mean that you have to explain how syntax and code and languages work. We aren't making a tutorial. However, it means that
* On the top of a file we should explain what the file is supposed to do
* On the top of a function or class we should explain what the function / class does and what the function arguments mean and what arguments are required
* important: the variable and function names should be self-explanatory
* Any line or block whose meaning isn't easily discernible should be commented. You don't need to explain in detail how it works, just what it is supposed to do.

Again, you don't need to explain basic syntax or anything.

Do you agree that we should comment this way?

By the way, I didn't understand something myself, namely what the file .styleintrc does. I couldn't find an explanation on google. Is the file name correct? And I was going to ask what that file does (as I said I'm a beginner too :D but maybe you could just answer that in a comment in the file so that everyone can see it right away. :)

If you agree to the commenting suggestion then I will add them to the contributing guidelines. Also, we start to write code in other branches than main and the good commenting will be one of the requirements that is checked by someone else than the author before merging.

**Comment by olgierd-on-fire** [comment]
I think that coding is like writing. @Aliin, did you read Clean Code book?

**Comment by Mortiferr** [comment]
I will add this to the CONTRIBUTING.md file.

**Comment by Aliin** [comment]
Good.
