### ISSUE TITLE
Misexpressed myself

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#26]
I recently said that you should make your own forks before you commit to master, but I misused the github terminology. I meant you should create branches. Sorry.

**Comment by olgierd-on-fire** [comment]
I feel difficult to manage branches, commits, and some collisions when I commit, push, and pull etc.
A few hours ago, Finally I understand how to push and pull to my fork repo and remote upstream repo.

**Comment by Aliin** [comment]
AHHH yes I have the problem now I'm working in an online environment now with just the command line so i have to figure out how to upload the changes I made
