### ISSUE TITLE
Database Setup finished

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#29]
I finished the first version of the database-setup. I will make a pull request to master, please review the code if it is okay and works. Security leaks will have to be addressed, mainly sql-injections, but we can do that later. Also, it is meant for developers so you wouldn't want to break your own server intentionally anyway, so that's no big deal. If you want to start developing, just install a WAMP server or something, put the branch "Database-Setup" or "Display-Posts" or "Submit-Posts" into the www directory of your server and type "localhost/mysql_setup.php" and follow the instructions.

**Comment by olgierd-on-fire** [comment]
I've just test it works. If you merge with master, then mysql-setup.php will be placed in database directory? or / directory?

**Comment by Aliin** [comment]
/directory for now so the developers can find it immediately
