### ISSUE TITLE
Pull Request Labels

### ISSUE THREAD

**Issue by Mortiferr** [Aliin/Symposium#31]
We need to add labels such as frontend and backend to the pull requests so that when we have more requests we can quickly see who is in charge of the requests. For example #30 that's backend stuff so I have no idea on how to do that.

**Comment by Aliin** [comment]
Okay.

**Comment by Mortiferr** [comment]
What I meant by labels are the little things on the right sidebar, the thing right above milestone. You can add them in the repo settings.

**Comment by Mortiferr** [comment]
https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by Aliin** [comment]
thanks
