### ISSUE TITLE
Reorganization (important!)

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#37]
Hopefully we can have a Chat session this Weekend on how to organize our Project well. However, we can make suggestions or post ideas here already. The Problems are:
* Do we use MVC from the start?
* If so, what MVC Features do we want to include?
* If not, how do we organize our Folder structure? I think it Needs a better System.
* Do we use a PHP Framework like Zend? If so, do we apply it from the start or later?
* If so, will we use a lightweight Framework like codeignite or a heavyweight like Zend or CakePHP? (I prefer a lightweight much.)
* How do we make the frontend and backend compatible / cooperate?
* Which PHP Version do we use? 5 or 7?
* What else?

**Comment by Aliin** [comment]
I prefer CodeIgnite, but not from the start. That is because I want to learn the fundamentals before I start a framework and also Zend does so much for you that you can't work on the fundamentals yourself and is complicated. Maybe we can use Zend in a much later version or project. I would like to reorganize our code to MVC Folder structure right away, but for now without a Framework or autoloader etc. However, I would like to make a config file that holds e.g. the paths of the files as constants so we can Change them easily when needed. Also, how and when do we implement user Login and sessions and Cookies? I don't really know how that works yet.

**Comment by olgierd-on-fire** [comment]
Yes, We have own goals and to learn fundamentals of PHP is also I want.
Below is my suggestion.

1. Do we use MVC from the start?
=> We don't need MVC yet.
[MVC](https://en.wikipedia.org/wiki/Model–view–controller) is also a pattern of application architectures. This means it's not essential. We don't know yet how Symposium is gonna be well known to the people and accomplish goals.

2. If so, what MVC Features do we want to include?
=> We just apply MVC architecture to our project not feature. Model is related to data or database, View is user interface related to HTML and CSS, and Controller is a relay that respond to user requests. MVC is just like a bone or a skeleton.

3. If not, how do we organize our Folder structure? I think it Needs a better System.
=> If we will use Zend or anything, then like this: [Recommended Project Directory Structure](http://framework.zend.com/manual/1.12/en/project-structure.project.html)
=> If we won't use Zend or any frameworks, then we will make it(what we will create features).

4. Do we use a PHP Framework like Zend? If so, do we apply it from the start or later?
=> We will make sure that why we need a framework? Where to use that for? If so, we apply it from the start. Because the project is now beginning.

5. If so, will we use a lightweight Framework like codeignite or a heavyweight like Zend or CakePHP? (I prefer a lightweight much.)
=> Check this up: [PHP The Right Way: Frameworks](http://www.phptherightway.com/#frameworks)

6. How do we make the frontend and backend compatible / cooperate?

7. Which PHP Version do we use? 5 or 7?
=> Try to check [PHP The Right Way: Getting Started](http://www.phptherightway.com/#getting_started).

8. What else?

**Comment by olgierd-on-fire** [comment]
Also we need to reorganize roadmap and milestone.

**Comment by Aliin** [comment]
Yes, I would like to use an MVC Skeleton from now on, just so the files are better organized. It makes a lot of sense to have that Kind of Folder structure and to not have the html code for every page copied but use include and views. The link is great! Then I agree to use PHP 7. - I'm not sure about the Framework, while I like to use one so the code will be better it will make it harder to learn PHP stuff on my own. However, if I see how such a Framework functions, it will make it easier to create good PHP code on my own also. I found a comparison of different Frameworks: http://www.slant.co/topics/1183/~php-frameworks
I don't know if the site is accurate, but I like the Phalcon Framework. Three Points are important to me: - Good documentation - not very difficult to learn (both speaks against Zend) - Speed.
Phalcon is written in C mostly, which might have been a Problem, but I can write and read C code so that is fine for me. And C is fast! Anyway, since you seem to know more about Frameworks than me (I know nothing haha), you can decide which Framework to use if we use one.
So right now I'm not decided, but I'm leaning in the direction of using a Framework a bit. What about you? And yes, we have to organize our Roadmap and Milestone as well as our Folder structure. No big deal, because we only started on Friday and though I've written some code already, I haven't really thought the Project through yet, just decided to work on it and see what happens.

**Comment by Mortiferr** [comment]
As far as PHP 7 goes since PHP is a server side language all you guys have to do is make sure you're not using any of the deprecated classes and then it's the server owner's job to run PHP 7. Just code using non-deprecated classes and it will compatible with both.

**Comment by Mortiferr** [comment]
I like the idea of CodeIgniter, small, light, easy to learn but since I won't really be handling backend it's not up to me.

**Comment by Mortiferr** [comment]
I'm gonna wait to do any more design work until we decide how we're going to structure.

**Comment by olgierd-on-fire** [comment]
@Mortiferr What do you need to design? Do we need some prototyping tools?

**Comment by Mortiferr** [comment]
I kinda need a general idea of what it should look like. A wireframe of some sort. What prototyping tools did you have in mind?

**Comment by olgierd-on-fire** [comment]
I have no anything yet.

**Comment by olgierd-on-fire** [comment]
I was looking for real time collaboration prototyping tools.

**Comment by olgierd-on-fire** [comment]
@Mortiferr So we have to talk to get idea and plans today as @Aliin said.

**Comment by Aliin** [comment]
I like CodeIgniter too, as I said, but apparently it's a bit outdated (according to that page I linked.) But the most important aspect for a Framework is that it fits the Project it is for, and maybe for us it is good because we can still do a lot ourselves to learn and don't have to rely on the Framework for everything.

**Comment by Aliin** [comment]
As for the structure. Concerning the frontend. (I will later post this into the wiki if you agree on everything.)

1. I would like to have the HTML modularized.
 I'm already developing with that premise. That means that we have small reuseable modules that make up the site. So probably best is to make a whole html sample page first and then split the html by copy-paste into multiple files. I'll explain what I mean: Take the page that Displays the categories, which right now is index.php. Everything above and including the opening Body tag can be the html Header, a unique file including the actual Header to the site - banner, Navigation bar on top, whatever else. We can include this file in any other page we make up. Then we have as another html file just maybe a sidebar, which we can use on several pages as well. Then the footer with the closing html bottom. The General Body of the page will be another file, but if we have any repeating or reusable elements in it, they should also be a separate file. By that I mean stuff like categories displayed and Posts. To program them, I Need to refer to an html file which I can run in a Loop so it Displays the html for Posts as many times as required.

2. Data contained.
A post, for example, will Display some data, for example the post title, the username, the Content of the post. @Mortiferr you can decide how to Display that data and also what data will be displayed. You can then have us implement the code needed to do that. So you have total flexibility. When I have some code ready I will either paste the php variable that holds the data where you direct me to do it or if I already have the code ready first I will tell you what to paste as your variable Name into your html.

3. Pages.
Right now, at least as I'm working it, there will be a page that Shows the categories for the Posts - right now, of course, it is index.php. Later, there will be a welcoming page that links to the category page, but we can't be sure yet what we Need to put on it, so you can leave that for now mostly - or design a General style for it without doing anything specific. Next, we have a page that Displays the Posts (Topics). Then we will have a page that Displays one post with all replies/comments to it. Then we have a page with a create post(Topic) form, and a page with a create reply form. We have a SignUp form (no email verification for now, but later.) All of These pages Need to be designed, but the modularity of the html should make it a lot easier by just reusing a lot of elements.

**Comment by Aliin** [comment]
4. CSS: Patrick, you can have total flexibility with this, just I think it makes sense to not have a different css file for every page.
5. File structure: I created a config file in the display-Posts Directory that should hold all the paths to all the files in constants. It should be self-explanatory. If you add a new file, just make a constant like I did for it with it's path from the root Folder in the config file.
6. Include files: If you want to include a file (e.g. html module) in another, you should write
`` <?php require_once _________; ?>
In the gap you should first navigate to the root Directory. If you're two Folders down in the current file, write for "move up": `$MUP . $MUP`. the dot, surrounded by two spaces, means and. So you move up twice. Then you put in another dot and paste in the constant Name for the file you want that is in the config file. The whole Thing might look like this:
`` <?php require_once $MUP . $MUP . $MYFiLE; ?>
For this Thing to work, you have to put a reference to the config file on top of your file. So you write:
`` <?php require_once '../../config.php'; ?>
The difference here is that instead of $MUP you must write two dots and a slash for each Directory to the root, and enclose the file path in quotes.

**Comment by Mortiferr** [comment]
I feel like I'm in a little over my head :laughing: but I'll learn this.
