### ISSUE TITLE
VOTE ON FRAMEWORKS

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#40]
EDIT: We're still deciding what Frameworks etc to use. It will probably be: Mysql, Twig, CodeIgnite, and Foundation. We'll be working object-oriented, with an MVC structure (the last Point is not up for discussion.) Please take the Chance to look up the documentation for These Frameworks etc. If you have any objections to them or want to suggest something else, discuss it with us on Discord. You can vote for something else if you give a sensible reason. The final decision will be tomorrow, 8 pm CENTRAL EUROPEAN TIME. If you don't say anything we're deciding without you. This will be the FINL DECISION for the whole Project, we'll Change nothing Major afterwards anymore.

**Comment by Mortiferr** [comment]
Foundation for the frontend is good for me. Lots of elements, clean, easily restyleable, and lots of additonal jQuery plugins for easy use.

**Comment by xQuByte** [comment]
Foundation & Codeigniter

**Comment by Aliin** [comment]
Okay I think this is settled then.
