### ISSUE TITLE
Admin Structure

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#42]
Since we're doing a Forum Software, I want to clearly separate Server/super admins, admins, Moderators and so on. The Panel I'm making i think should be for the super admin who has the ultimate Access to databases, security, user permissions etc. as far as our Software will allow him or her. In the Panel I want to only include those functions to which ONLY the super admin has Access. Other stuff, like creating categories, is done by FORUM ADMINS, who have permission to Change everything about the Forum. Then there are Moderators further down below etc. The super admin has the ability to Permit or forbid stuff for other member-groups, as well as create a member Group with custom permissions.
So functionality that basically only goes to the super admin will be included on the admin Panel, everything that other members like Forum admins, or Moderators, can do, doesn't go on there.
I created an example of super admin Panel, what we might want to enable for the super admin in the future:
![admin1](https://cloud.githubusercontent.com/assets/19345795/16126838/2aea91d4-33fa-11e6-81e0-7f666e5f5fe4.JPG)
![admin2](https://cloud.githubusercontent.com/assets/19345795/16126843/34ba6b44-33fa-11e6-82f3-00a09c27a6f2.JPG)

Any comments or improvements?

**Comment by xQuByte** [comment]
Important think - naming
Controller: Admin.php
Model: Admin_model.php
View: (example) Admin/index

Remember about that :)

**Comment by olgierd-on-fire** [comment]
Nice idea plugins and add ons.

Delete a user.

**Comment by Aliin** [comment]
Okay thanks. I understood the naming conventions in General but your Suggestion makes sense, I'll Change it. User deletion can be under edit.

**Comment by Mortiferr** [comment]
Closing, because rip project

**Comment by olgi3rd** [comment]
@Mortiferr How are you?

**Comment by Mortiferr** [comment]
Pretty good, what about you?

**Comment by olgi3rd** [comment]
@Mortiferr I'm fine.

**Comment by Mortiferr** [comment]
I'm very concerned for America right now.

**Comment by olgi3rd** [comment]
@Mortiferr I saw Trump is now the president. I agree with you.

**Comment by profoundhub** [comment]
I hope Trump can make America great again too!

**Comment by Mortiferr** [comment]
@profoundhub Hopefully.
