### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#6]
We're looking for a catchy Name for our php site - and the site, as we just decided, won't be just a Forum but a Forum-building kit centered on Topics like webdevelopment and design.

**Comment by Mortiferr** [comment]
I thought about the word "Symposium" simply as our name. For those of you who don't know that means a meeting or a place where things are discussed.

**Comment by Aliin** [comment]
Let's just add a working title, okay? Call it Symposium for now - or something - and Change the title when we come up with something good?

**Comment by Mortiferr** [comment]
Sounds good to me.
