### ISSUE TITLE
Future ideas: drop-down unfolding of categories

### ISSUE THREAD

**Issue by Aliin** [Aliin/Symposium#7]
At the beginning the cateory clicking will probably lead to another site that Displays the Posts that belong to that category. That is what happens in the discourse Forums (see http://community.gemsofwar.com/categories). But wouldn't it be nicer if the page wouldn't reload and instead the category would just open to add all the Posts? I'm sure thats manageable with php and js.

**Comment by Mortiferr** [comment]
Does this need to stay open or should this just go on the roadmap somewhere?

**Comment by Aliin** [comment]
Seems like a good idea. Right now i am so new with all of this that I don't know yet where everything belongs。I won‘t put it on the roadmap though but on a new wiki page future ideas。
